language:
  python
python:
  - "3.9"
install:
  - pip install numpy
  - pip install -r requirements.txt
  - python setup.py build_ext
ignore:
  - pmaf/internal/_extensions/*
script:
  - pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
